package ba.unsa.etf.rpr.Bussiness;

import ba.unsa.etf.rpr.Exceptions.RailwayException;
import ba.unsa.etf.rpr.dao.DaoFactory;
import ba.unsa.etf.rpr.domain.Train;

import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
/**
 * Business Logic Layer for management of Trains
 * @author Hana Catic
 * */
public class TrainManager {
    /**
     * Validates name of train
     * @param name of train
     * @throws RailwayException - train name must be between 1 and 60 chars
     * */
    public void validateTrainName(String name) throws RailwayException {
        if(name == null || name.length() > 60 || name.length() < 1){
            throw new RailwayException("Train name must be between 1 and 60 chars.");
        }
    }
    /**
     * Validates date of train purchase
     * @param dateBought date the of the purchase of a train
     * @throws RailwayException - purchase can only be in the past it cannot be in the future
     * */
    public void validateTrainDateBought(Date dateBought) throws RailwayException {
        if(dateBought == null || dateBought.toLocalDate().isAfter(LocalDate.now(ZoneId.systemDefault()))){
            throw new RailwayException("Date of train purchase cannot be in the future.");
        }
    }
    /**
     * Adds an entry to trains table in database
     * @param train to be added
     * @throws RailwayException
     * */
    public Train add(Train train) throws RailwayException {
        if(train.getId() != 0){
            throw new RailwayException("Train with Id cannot be added. Id is autogenerated");
        }
        validateTrainName(train.getName());
        validateTrainDateBought(train.getDateBought());
        try{
            return DaoFactory.trainDao().add(train);
        }catch(RailwayException e){
            if(e.getMessage().contains("UNIQUE")){
                throw new RailwayException("Train with the same name exists.");
            }
            throw e;
        }
    }
    /**
     * Deletes an entry from trains table in database
     * @param trainId of train to be deleted
     * @throws RailwayException
     * */
    public void delete(int trainId) throws RailwayException {
        try{
            DaoFactory.trainDao().delete(trainId);
        } catch (RailwayException e) {
            if(e.getMessage().contains("FOREIGN KEY")){
                throw new RailwayException("Cannot delete a train related to journeys. Delete all journeys related to a train before deleting a train.");
            }
            throw e;
        }
    }
    /**
     * Updates an entry in trains table in database
     * @param train to be updated
     * @throws RailwayException
     * */
    public Train update(Train train) throws RailwayException {
        validateTrainName(train.getName());
        validateTrainDateBought(train.getDateBought());
        return DaoFactory.trainDao().update(train);
    }
    /**
     * Gets all trains from database
     * @throws RailwayException
     * */
    public List<Train> getAll() throws RailwayException {
        return DaoFactory.trainDao().getAll();
    }
    /**
     * Gets an entry from trains table in database
     * @param id of entry in database
     * @throws RailwayException
     * */
    public Train getById(int id) throws RailwayException {
         return DaoFactory.trainDao().getById(id);
    }
}
